#!/bin/bash

#
# Automatically add ticket refs to commit messages based on your branch name.
#
# All that is required is that your branch ends in -[0-9]+, which is your
# ticket number.
#

BRANCH=`git rev-parse --abbrev-ref HEAD`
MESSAGE_FILE="$1"

# Don't add if a ticket ref already found (eg in an --amend)
if grep -E '\[#[0-9]+\]' "$MESSAGE_FILE"; then
	exit 0
fi

if [[ "$BRANCH" =~ -[0-9]+$ ]]; then
	TICKET="$(echo $BRANCH | grep -Eo '[0-9]+$')"
	
	# PivotalTracker
	TICKET_STRING="[#$TICKET]"
	
	# Redmine
	# TICKET_STRING="Refs: #$TICKET"
	
	echo -e "$TICKET_STRING \n$(cat $MESSAGE_FILE)" > $MESSAGE_FILE
fi
