#!/bin/bash

BRANCH=`git rev-parse --abbrev-ref HEAD`
MESSAGE_FILE="$1"
if [[ "$BRANCH" =~ -[0-9]+$ ]]; then
	TICKET="$(echo $BRANCH | grep -Eo '[0-9]+$')"
	echo -e "[#$TICKET] \n$(cat $MESSAGE_FILE)" > $MESSAGE_FILE
fi

